baseURL = "https://danchenkov-oceanography.ru/"
amp = true
ampCdnRoot = "https://cdn.ampproject.org/"
languageCode = "ru-ru"
title = "Данченков Михаил Алексеевич. Океанография Дальнего Востока"
theme = ["hugo-search-fuse-js", "basic"]
description = "Данченков Михаил Алексеевич (2.1.1950-)"
googleAnalytics = "UA-157724393-1"
disableKinds = ["taxonomy", "taxonomyTerm"]
[outputs]
	home = ["HTML", "AMP", "RSS", "JSON"]
	page = ["HTML", "AMP"]

[module]
	[[module.mounts]]
        source = "assets/images"
        target = "static/images"