baseURL = "https://danchenkov-oceanography.ru/"
amp = true
ampCdnRoot = "https://cdn.ampproject.org/"
languageCode = "ru-ru"
title = "Данченков Михаил Алексеевич. Океанография Дальнего Востока"
theme = ["hugo-search-fuse-js", "basic"]
timeout = 20000
description = "Данченков Михаил Алексеевич (2.1.1950-)"
googleAnalytics = "UA-157724393-1"
disableKinds = ["taxonomy", "taxonomyTerm"]
[outputs]
	home = ["html", "amp", "rss", "json"]
	page = ["html", "amp"]

[module]
#	[[module.mounts]]
#		source = "assets/images"
#		target = "static/images"

#	[[module.mounts]]
#		source = "assets/fonts"
#		target = "static/fonts"

#	[[module.mounts]]
#		source = "node_modules/@popperjs/core/dist"
#		target = "assets/popperjs"

#	[[module.mounts]]
#		source = "node_modules/bootstrap/dist/js/bootstrap.min.js"
#		target = "assets/vendor/bootstrap/dist/js/bootstrap.min.js"
